---
- name: Manage ssh
  block:
  - name: Disable root login
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#?PermitRootLogin'
      line: 'PermitRootLogin no'
      state: present

  - name: Disable empty passwords
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#?PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
      state: present

  - name: Set logging level to VERBOSE
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#?LogLevel'
      line: 'LogLevel VERBOSE'
      state: present

  - name: Disable X11 Forwarding
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#?X11Forwarding'
      line: 'X11Forwarding no'
      state: present
  notify: Restart SSH server